version: '1.0'
services:
  gerenciador-service:
    image: murilonerdx/gerenciador-service
    restart: always
    build: ./
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Test
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - gerenciador-network
networks:
  gerenciador-network:
    driver: bridge